# Generated by Django 2.2.7 on 2019-12-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baconBack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='classID',
            field=models.CharField(default='NULL', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='classID',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='member',
            name='userID',
            field=models.CharField(max_length=40),
        ),
    ]

