# Generated by Django 2.2.7 on 2019-12-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baconBack', '0002_attendance_class_member_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lineID',
        ),
        migrations.AddField(
            model_name='user',
            name='ID',
            field=models.CharField(default='null', max_length=40, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='studentID',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]

