# Generated by Django 2.2.7 on 2019-12-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baconBack', '0002_auto_20191219_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]

