# Generated by Django 2.2.7 on 2019-12-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baconBack', '0003_auto_20191219_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='classID',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]

