# Generated by Django 2.2.7 on 2019-12-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baconBack', '0005_auto_20191218_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='classID',
            field=models.IntegerField(),
        ),
    ]

