# Generated by Django 2.2.7 on 2019-12-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baconBack', '0006_auto_20191218_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]

